### PR TITLE
FIX : Layout should be more mobile friendly on item page #603

### LINKED ISSUE #603: Layout should be more mobile friendly on item page
### Description
Remove margins on mobile
Remove not important infomation on mobile page 
Reorder the item on page.

#### For which stakeholder (people, role, project, domain) is it important?
This is crucial for mobile users.

#### Expected behavior
It's expected that the item page is clean with important information only.

#### Environment
 - OS: [e.g. Windows 10, macOS 10.15, iOS]
 - Browser: [e.g. chrome 88, safari 14]

#### Phase 1
- [x] Mock-up
- [x] Implementation strategy

#### Phase 2
- [ ] Acceptance tests (Capybara)
- [ ] Implementation

### PR DESCRIPTION
**Pull request by Couapy**
Co-authored-by: Maël Marchand <mael.marchand@utt.fr>
Co-authored-by: Thomond5 <Thomond5@users.noreply.github.com>
Co-authored-by: LucasJeanpierre <lulu.jeanpierre@gmail.com>
Co-authored-by: IrisBR <IrisBR@users.noreply.github.com>

## Content

Make mobile usage friendly. Please see #603

---

## Checklist

Please check that your pull request is correct:

- Each commit:
    - [x] corresponds to a contribution that should be notified to users,
    - [x] does not generate new errors or warnings at compile or test time,
    - [x] must be attributed to its real authors (with correct GitHub IDs and [correct syntax for multiple authors](https://help.github.com/articles/creating-a-commit-with-multiple-authors/)).
- The title of a commit should:
    - [x] begin with a contribution type
        - `FEATURE` for a behaviour allowing a user to do something new,
        - `FIX` for a behaviour which has been changed in order to meet user’s expectations,
        - `SCENARIO` for examples showing a given behaviour,
        - `TEST` when it concerns an acceptance test of a given behaviour,
        - `PROCESS` for a change in the way the software is built, tested, deployed,
        - `DOC` when it concerns only internal documentation (however it is better to combine it with the contribution that required this documentation change),
    - [x] be followed by a colon (`:`) with one space after and no space before,
    - [x] be followed by a title (written in English) as short, as user-centered and as explicit as possible
        - If it is a feature, the title must be the user action (beginning with a verb, and please not `manage`),
        - If it is a fix, the title must describe the intended behavior (with `should`).
    - [x] ends with a reference to the corresponding ticket with the following syntax:
        - `(closes #xx)` if xx is a feature ticket (and the commit is a complete implementation),
        - `(fixes #xx)` if xx is a fix ticket (and the commit is a complete fix),
        - `(see #xx)` otherwise,
- Each committed line is:
    - [x] useful (it would not work if removed)
        - if it is a comment line, its information could not be conveyed by better variables and function naming, better code structuring, or better commit message,
    - [x] related to this very contribution (feature, fix...),
    - [x] in English (with the exception of Gherkin scenarios in French and resulting steps),
    - [x] without any typo in variable, class or function names,
    - [x] correctly indented (spaces rather than tabs, same number of characters as in the rest of the file).

### CODE REVIEW

**Review by benel — CHANGES_REQUESTED** [review]
Thank you very much for this contribution that will be useful VERY soon...

A small question however: What happened to the CSS, did you really change every line of code? Or maybe you had a problem with CRLF settings in git? Could you please fix that?

**Comment by Couapy** [comment]
I fixed it, is it ok?

File: src/components/itemPage/Item.jsx [hunk 1]
```diff
@@ -111,7 +121,7 @@ class Item extends Component {
     return new Items([this.state.item]).getAttributes()
       .map(x => (
         <Attribute key={x[0]} name={x[0]} value={x[1]}
-          setAttribute={this._setAttribute} deleteAttribute={this._deleteAttribute}/>
+          setAttribute={this._setAttribute} deleteAttribute={this._deleteAttribute} />
```
Comment (benel) [inline src/components/itemPage/Item.jsx:124]: Petite remarque : Il est déconseillé d'inclure dans un commit une ligne qui n'a pas de rapport avec le sujet du commit. Dans ce cas précis, cela a créé un conflit de modification qui aurait pu être évité. Merci :)

Note : ce message est juste informatif. Ce n'est pas une demande de modification.

**Review by benel — APPROVED** [review]
